#
# Module manifest for module 'WebAssetBuilder'
#
# Generated by: SRNP
#
# Generated on: 18/08/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'WebAssetBuilder.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '76913085-5948-417e-a92b-15201ab4a1f4'

# Author of this module
Author = 'SRNP'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) SRNP. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Build automation for HAML, Stylus, and TypeScript'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Invoke-HamlBuild',
    'Invoke-StylusBuild',
    'Invoke-TypeScriptBuild',
    'Invoke-WebAssetsValidation'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Build', 'Automation', 'WebAssets', 'HAML', 'Stylus', 'TypeScript')

        # A URL to the license for this module.
        LicenseUri = 'https://unlicense.org'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/custom-tours-web/ui'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @"
        1.0.0 Release Notes:
        - Initial production release.
        - Added Invoke-HamlBuild, Invoke-StylusBuild, and Invoke-TypeScriptBuild.
        - Added Invoke-WebAssetsValidation for distribution checks.
"@

        # Prerelease string of this module
        Prerelease = 'preview1'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

    # Embedded Pester Configuration
    Pester = @{
        Run = @{
            Path = './Tests/Integration/Invoke-WebAssetsValidation.Tests.ps1'
            Throw = $true
            Exit = $true
            PassThru = $true
        }
        Debug = @{
            WriteDebugMessages = $true
            ShowNavigationMarkers = $true
            ShowStartMarkers = $true
            ReturnRawResultObject = $true
        }
        Output = @{
            ShowTags = $true
            StackTraceVerbosity = 'Full'
            Verbosity = 'Diagnostic'
            CILogLevel = 'Warning'
            CIFormat = 'GithubActions'  # Enables native GitHub Actions PR annotations
            RenderMode = 'ConsoleColor'
        }
        TestResult = @{
            Enabled = $true
            OutputFormat = 'NUnitXml'   # Standard format required by most CI tools
            OutputPath = './TestResults/result.xml'
        }
        CodeCoverage = @{
            Enabled = $true
            Path = './public/Invoke-WebAssetsValidation.ps1' # Restricts coverage scan to module code, ignoring tests
            OutputPath = './TestResults/coverage.xml'
        }
        Should = @{
            ErrorAction = 'Continue'
            DisableV5 = $true           # Enforces legacy Pester 4 assertion syntax
        }
    } # End of Pester hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
