BeforeAll {
    Import-Module "$PSScriptRoot/../../WebAssetBuilder.psd1" -Force

    function stylus {}

    InModuleScope 'WebAssetBuilder' {
        function stylus {}
    }
}

Describe 'Invoke-StylusBuild Integration Tests' {
    
    BeforeEach {
        # $TestDrive is a real absolute path generated by Pester for this specific test block
        $script:tempRoot = $TestDrive

        # Create the 'src' folder inside the TestDrive so Find-ProjectRoot succeeds
        $script:srcDir = Join-Path $script:tempRoot "src"
        New-Item -ItemType Directory -Path $script:srcDir -Force | Out-Null
    }

    AfterEach {
        # Clean up files so the next test starts with a blank slate
        Get-ChildItem -Path $TestDrive -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force
    }

    # ----------------------------------------------------------------------
    # SCENARIO 1: Invalid Project Root
    # ----------------------------------------------------------------------
    It 'Should throw an error when the project root cannot be determined' {
        Mock Get-Command { return $true } -ParameterFilter { $Name -eq 'stylus' }
        
        # Forces the project root lookup to fail.
        Mock Find-ProjectRoot { return $null } -ModuleName 'WebAssetBuilder'

        { Invoke-StylusBuild -StartPath $script:tempRoot } | 
            Should-Throw 'Project root could not be determined.'
    }

    # ----------------------------------------------------------------------
    # SCENARIO 2: Missing Source Directory
    # ----------------------------------------------------------------------
    It 'Should throw an error when the Stylus source directory does not exist' {
        Mock Get-Command { return $true } -ParameterFilter { $Name -eq 'stylus' }
        
        # The target source directory 'src/styl' is deliberately not created.
        { Invoke-StylusBuild -StartPath $script:tempRoot } | 
            Should-Throw "Stylus source directory not found:*"
    }

    # ----------------------------------------------------------------------
    # SCENARIO 3: No Stylus Files Found
    # ----------------------------------------------------------------------
    It 'Should throw an error when the source directory is empty' {
        Mock Get-Command { return $true } -ParameterFilter { $Name -eq 'stylus' }

        $stylSrcDir = Join-Path $script:tempRoot "src/styl"
        New-Item -ItemType Directory -Path $stylSrcDir -Force | Out-Null

        # Verifies the script throws when no .styl files are present to compile.
        { Invoke-StylusBuild -StartPath $script:tempRoot } | 
            Should-Throw "No Stylus files found in:*"
    }

    # ----------------------------------------------------------------------
    # SCENARIO 4: The Happy Path
    # ----------------------------------------------------------------------
    It 'Should compile Stylus files to CSS successfully' -Skip:(-not (Get-Command 'stylus' -ErrorAction SilentlyContinue)) {
        $stylSrcDir = Join-Path $script:tempRoot "src/styl"
        New-Item -ItemType Directory -Path $stylSrcDir -Force | Out-Null

        $validStylFile = Join-Path $stylSrcDir "test.styl"
        Set-Content -Path $validStylFile -Value "body`n  color red"

        Invoke-StylusBuild -StartPath $script:tempRoot

        # Verifies that the default 'dist/css' output folder is created properly.
        $cssDistDir = Join-Path $script:tempRoot "dist/css"
        Test-Path $cssDistDir -PathType Container | Should-BeTrue

        $compiledCssFile = Join-Path $cssDistDir "test.css"
        Test-Path $compiledCssFile -PathType Leaf | Should-BeTrue
    }
}