BeforeAll {
    Import-Module "$PSScriptRoot/../../WebAssetBuilder.psd1" -Force
}

Describe 'Invoke-WebAssetsValidation Integration Tests' {
    
    BeforeEach {
        # $TestDrive is a real absolute path generated by Pester for this specific test block
        $script:tempRoot = $TestDrive

        # Create the 'src' folder inside the TestDrive so Find-ProjectRoot succeeds
        $script:srcDir = Join-Path $script:tempRoot "src"
        New-Item -ItemType Directory -Path $script:srcDir -Force | Out-Null
    }

    AfterEach {
        # Clean up files so the next test starts with a blank slate
        Get-ChildItem -Path $TestDrive -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force
    }

    # ----------------------------------------------------------------------
    # SCENARIO 1: Invalid Project Root
    # ----------------------------------------------------------------------
    It 'Should throw an error when the project root cannot be determined' {
        # Force Find-ProjectRoot to fail for this specific test
        Mock Find-ProjectRoot { return $null } -ModuleName "WebAssetBuilder"

        { Invoke-WebAssetsValidation -StartPath $script:tempRoot } | 
            Should -Throw 'Project root could not be determined.'
    }

    # ----------------------------------------------------------------------
    # SCENARIO 2: Missing 'dist' Directory
    # ----------------------------------------------------------------------
    It 'Should throw an error when the dist directory does not exist' {
        # We purposely do not create a 'dist' folder here
        
        { Invoke-WebAssetsValidation -StartPath $script:tempRoot } | 
            Should -Throw "Final dist directory was not created:*"
    }

    # ----------------------------------------------------------------------
    # SCENARIO 3: Missing HTML Files
    # ----------------------------------------------------------------------
    It 'Should throw an error when no HTML files are found in dist' {
        $distPath = Join-Path $script:tempRoot "dist"
        New-Item -ItemType Directory -Path $distPath -Force | Out-Null

        # Create CSS and JS, but skip HTML
        New-Item -ItemType File -Path (Join-Path $distPath "style.css") -Force | Out-Null
        New-Item -ItemType File -Path (Join-Path $distPath "app.js") -Force | Out-Null

        { Invoke-WebAssetsValidation -StartPath $script:tempRoot } | 
            Should -Throw 'No HTML files found in final dist.'
    }

    # ----------------------------------------------------------------------
    # SCENARIO 4: Missing CSS Files
    # ----------------------------------------------------------------------
    It 'Should throw an error when no CSS files are found in dist' {
        $distPath = Join-Path $script:tempRoot "dist"
        New-Item -ItemType Directory -Path $distPath -Force | Out-Null

        # Create HTML and JS, but skip CSS
        New-Item -ItemType File -Path (Join-Path $distPath "index.html") -Force | Out-Null
        New-Item -ItemType File -Path (Join-Path $distPath "app.js") -Force | Out-Null

        { Invoke-WebAssetsValidation -StartPath $script:tempRoot } | 
            Should -Throw 'No CSS files found in final dist.'
    }

    # ----------------------------------------------------------------------
    # SCENARIO 5: Missing JavaScript Files
    # ----------------------------------------------------------------------
    It 'Should throw an error when no JS files are found in dist' {
        $distPath = Join-Path $script:tempRoot "dist"
        New-Item -ItemType Directory -Path $distPath -Force | Out-Null

        # Create HTML and CSS, but skip JS
        New-Item -ItemType File -Path (Join-Path $distPath "index.html") -Force | Out-Null
        New-Item -ItemType File -Path (Join-Path $distPath "style.css") -Force | Out-Null

        { Invoke-WebAssetsValidation -StartPath $script:tempRoot } | 
            Should -Throw 'No JavaScript files found in final dist.'
    }

    # ----------------------------------------------------------------------
    # SCENARIO 6: The Happy Path (Success)
    # ----------------------------------------------------------------------
    It 'Should execute successfully when all asset types are present' {
        $distPath = Join-Path $script:tempRoot "dist"
        New-Item -ItemType Directory -Path $distPath -Force | Out-Null

        # Create all required file types
        New-Item -ItemType File -Path (Join-Path $distPath "index.html") -Force | Out-Null
        New-Item -ItemType File -Path (Join-Path $distPath "style.css") -Force | Out-Null
        New-Item -ItemType File -Path (Join-Path $distPath "app.js") -Force | Out-Null

        { Invoke-WebAssetsValidation -StartPath $script:tempRoot } | 
            Should -Not -Throw
    }
}
