BeforeAll {
    Import-Module "$PSScriptRoot/../../WebAssetBuilder.psd1" -Force
}

Describe 'Invoke-HamlBuild Integration Tests' {
    
    BeforeEach {
        # $TestDrive is a real absolute path generated by Pester for this specific test block
        $script:tempRoot = $TestDrive

        # Create the 'src' folder inside the TestDrive so Find-ProjectRoot succeeds
        $script:srcDir = Join-Path $script:tempRoot "src"
        New-Item -ItemType Directory -Path $script:srcDir -Force | Out-Null
    }

    AfterEach {
        # Clean up files so the next test starts with a blank slate
        Get-ChildItem -Path $TestDrive -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force
    }

    # ----------------------------------------------------------------------
    # SCENARIO 1: Invalid Project Root
    # ----------------------------------------------------------------------
    It 'Should throw an error when the project root cannot be determined' {
        Mock Get-Command { return $true } -ParameterFilter { $Name -eq 'haml' }
        
        # Forces the project root lookup to fail.
        Mock Find-ProjectRoot { return $null } -ModuleName 'WebAssetBuilder'

        { Invoke-HamlBuild -StartPath $script:tempRoot } | 
            Should-Throw 'Project root could not be determined.'
    }

    # ----------------------------------------------------------------------
    # SCENARIO 2: Missing Source Directory
    # ----------------------------------------------------------------------
    It 'Should throw an error when the HAML source directory does not exist' {
        Mock Get-Command { return $true } -ParameterFilter { $Name -eq 'haml' }
        
        # The target source directory 'src/haml' is deliberately not created.
        { Invoke-HamlBuild -StartPath $script:tempRoot } | 
            Should-Throw "HAML source directory not found:*"
    }

    # ----------------------------------------------------------------------
    # SCENARIO 3: No HAML Files Found
    # ----------------------------------------------------------------------
    It 'Should throw an error when the source directory is empty' {
        Mock Get-Command { return $true } -ParameterFilter { $Name -eq 'haml' }

        $hamlSrcDir = Join-Path $script:tempRoot "src/haml"
        New-Item -ItemType Directory -Path $hamlSrcDir -Force | Out-Null

        # Verifies the script throws when no .haml files are present to compile.
        { Invoke-HamlBuild -StartPath $script:tempRoot } | 
            Should-Throw "No HAML files found in:*"
    }

    # ----------------------------------------------------------------------
    # SCENARIO 4: The Happy Path
    # ----------------------------------------------------------------------
    It 'Should compile HAML files to HTML successfully and preserve relative structures' -Skip:(-not (Get-Command 'haml' -ErrorAction SilentlyContinue)) {
        $hamlSrcDir = Join-Path $script:tempRoot "src/haml"
        New-Item -ItemType Directory -Path $hamlSrcDir -Force | Out-Null

        # Create a root file and a nested file to verify relative path structures.
        $validRootFile = Join-Path $hamlSrcDir "test.haml"
        Set-Content -Path $validRootFile -Value "%h1 Root"

        Invoke-HamlBuild -StartPath $script:tempRoot

        # Verifies that the default 'dist' output folder is created.
        $htmlDistDir = Join-Path $script:tempRoot "dist"
        Test-Path $htmlDistDir -PathType Container | Should-BeTrue

        # Verifies root file compilation.
        $compiledRootFile = Join-Path $htmlDistDir "test.html"
        Test-Path $compiledRootFile -PathType Leaf | Should-BeTrue
    }
}