BeforeAll {
    Import-Module "$PSScriptRoot/../../WebAssetBuilder.psd1" -Force
}

Describe 'Invoke-TypeScriptBuild Integration Tests' {
    
    BeforeEach {
        # $TestDrive is a real absolute path generated by Pester for this specific test block
        $script:tempRoot = $TestDrive

        # Create the 'src' folder so 'Find-ProjectRoot' successfully identifies this as a valid project
        $script:srcDir = Join-Path $script:tempRoot "src"
        New-Item -ItemType Directory -Path $script:srcDir -Force | Out-Null
    }

    AfterEach {
        # Clean up files so the next test starts with a blank slate
        Get-ChildItem -Path $TestDrive -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force
    }

    # ----------------------------------------------------------------------
    # SCENARIO 1: Invalid Project Root
    # ----------------------------------------------------------------------
    It 'Should throw an error when the project root cannot be determined' {
        # Ensure tsc check passes so it reaches the Find-ProjectRoot logic
        Mock Get-Command { return $true } -ParameterFilter { $Name -eq 'tsc' }
        
        # Force Find-ProjectRoot to fail
        Mock Find-ProjectRoot { return $null } -ModuleName 'WebAssetBuilder'

        { Invoke-TypeScriptBuild -StartPath $script:tempRoot } | 
            Should-Throw 'Project root could not be determined.'
    }

    # ----------------------------------------------------------------------
    # SCENARIO 2: Missing Source Directory
    # ----------------------------------------------------------------------
    It 'Should throw an error when the TypeScript source directory does not exist' {
        Mock Get-Command { return $true } -ParameterFilter { $Name -eq 'tsc' }
        
        # The default source directory 'src/ts' is intentionally NOT created here
        { Invoke-TypeScriptBuild -StartPath $script:tempRoot } | 
            Should-Throw "TypeScript source directory not found:*"
    }

    # ----------------------------------------------------------------------
    # SCENARIO 3: No TypeScript Files Found
    # ----------------------------------------------------------------------
    It 'Should throw an error when the source directory is empty' {
        Mock Get-Command { return $true } -ParameterFilter { $Name -eq 'tsc' }

        # Create the source directory, but add zero .ts files to it
        $tsSrcDir = Join-Path $script:tempRoot "src/ts"
        New-Item -ItemType Directory -Path $tsSrcDir -Force | Out-Null

        { Invoke-TypeScriptBuild -StartPath $script:tempRoot } | 
            Should-Throw "No TypeScript files found in:*"
    }

    # ----------------------------------------------------------------------
    # SCENARIO 4: The Happy Path
    # ----------------------------------------------------------------------
    It 'Should compile TypeScript files to JavaScript successfully' -Skip:(-not (Get-Command 'tsc' -ErrorAction SilentlyContinue)) {
        # Create the source directory
        $tsSrcDir = Join-Path $script:tempRoot "src/ts"
        New-Item -ItemType Directory -Path $tsSrcDir -Force | Out-Null

        # Create a valid TypeScript file
        $validTsFile = Join-Path $tsSrcDir "test.ts"
        Set-Content -Path $validTsFile -Value "const greeting: string = 'Hello World';"

        # Execute the function; it should not throw any exceptions
        Invoke-TypeScriptBuild -StartPath $script:tempRoot

        # Assert that the dist/js directory was created
        $jsDistDir = Join-Path $script:tempRoot "dist/js"
        Test-Path $jsDistDir -PathType Container | Should-BeTrue

        # Assert that the compiled JavaScript file exists
        $compiledJsFile = Join-Path $jsDistDir "test.js"
        Test-Path $compiledJsFile -PathType Leaf | Should-BeTrue
    }
}